server:
  port: 9411 #配置服务及端口（默认9411）

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

#去除控制台异常
management:
  metrics:
    web:
      server:
        auto-time-requests: false

#配置在数据库创建完以后，可以删除，不然每次都会寻找这个sql，耗费时间。
zipkin:
  storage:
    type: mysql
spring:
  datasource:
    url: jdbc:mysql://47.106.89.28:3306/zipkin-service
    username: root
    password: 123456
    initialize: false
    continueOnError: true
sleuth:
  enabled: true
